version: '3.8'

services:
  app:
    build:
      context: .
    image: eohsj-audiobook:latest
    restart: unless-stopped
    expose:         # <--- Change from 'ports' to 'expose'
      - "80"
    environment:
      - NODE_ENV=production
    labels:
      - "com.docker.compose.project=eohsj-audiobook"
